import { TransactionProps } from "./components/transaction-card/card";

export const transactionsMock: TransactionProps[] = [
    {
        amount: 9500,
        direction: 'plus',
        currency: 'ru',
        // title: 'Оплата по контракту',
        // description: 'Контракт #2891 от ООО "ТехноПрофи"',
        date: '2026-02-11 15:30:00',
        category: 'Доход',
        employee: {
            id: 'emp001',
            account_id: 'acc001',
            first_name: 'Александр',
            last_name: 'Иванов',
            email: 'alex@company.ru',
            phone: '+79161234567',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-12-15',
            updated_at: '2026-02-10',
            linked_at: '2025-12-20'
        }
    },
    {
        amount: 23450,
        direction: 'minus',
        currency: 'ru',
        // title: 'Закупка оборудования',
        // description: 'Офисная техника и оргтехника',
        date: '2026-02-11 14:15:22',
        category: 'Расход',
        employee: {
            id: 'emp002',
            account_id: 'acc002',
            first_name: 'Елена',
            last_name: 'Петрова',
            email: 'elena@company.ru',
            phone: '+79162345678',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-11-10',
            updated_at: '2026-02-09',
            linked_at: '2025-11-15'
        }
    },
    {
        amount: 5000,
        direction: 'minus',
        currency: 'ru',
        // title: 'Выплата зарплаты',
        // description: 'Аванс за февраль 2026',
        date: '2026-02-11 12:00:00',
        category: 'Зарплата',
        employee: {
            id: 'emp003',
            account_id: null,
            first_name: 'Сергей',
            last_name: 'Сидоров',
            email: 'sergey@company.ru',
            phone: '+79163456789',
            status: 'active',
            is_account_linked: false,
            created_at: '2026-01-20',
            updated_at: '2026-02-08',
            linked_at: null
        }
    },
    {
        amount: 7800,
        direction: 'plus',
        currency: 'us',
        // title: 'International payment',
        // description: 'Payment from TechCorp Inc.',
        date: '2026-02-11 10:45:33',
        category: 'Доход',
        employee: {
            id: 'emp004',
            account_id: 'acc004',
            first_name: 'John',
            last_name: 'Smith',
            email: 'john@company.ru',
            phone: '+79164567890',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-10-05',
            updated_at: '2026-02-07',
            linked_at: '2025-10-10'
        }
    },
    {
        amount: 12000,
        direction: 'minus',
        currency: 'kz',
        // title: 'Аренда помещения',
        // description: 'Филиал в Алматы',
        date: '2026-02-10 18:20:15',
        category: 'Аренда',
        employee: {
            id: 'emp005',
            account_id: 'acc005',
            first_name: 'Айгуль',
            last_name: 'Каримова',
            email: 'aigul@company.kz',
            phone: '+77011234567',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-09-15',
            updated_at: '2026-02-06',
            linked_at: '2025-09-20'
        }
    },
    {
        amount: 5600,
        direction: 'plus',
        currency: 'ea',
        // title: 'Европейский заказ',
        // description: 'Projekt #DE-2026-001',
        date: '2026-02-10 16:10:45',
        category: 'Доход',
        employee: {
            id: 'emp006',
            account_id: 'acc006',
            first_name: 'Thomas',
            last_name: 'Müller',
            email: 'thomas@company.de',
            phone: '+491701234567',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-08-25',
            updated_at: '2026-02-05',
            linked_at: '2025-08-30'
        }
    },
    {
        amount: 3200,
        direction: 'minus',
        currency: 'ru',
        // title: 'Коммунальные услуги',
        // description: 'Электроэнергия, вода, отопление',
        date: '2026-02-10 14:05:28',
        category: 'Коммуналка',
        employee: {
            id: 'emp007',
            account_id: null,
            first_name: 'Мария',
            last_name: 'Козлова',
            email: 'maria@company.ru',
            phone: '+79165678901',
            status: 'active',
            is_account_linked: false,
            created_at: '2026-01-15',
            updated_at: '2026-02-04',
            linked_at: null
        }
    },
    {
        amount: 8900,
        direction: 'plus',
        currency: 'ru',
        // title: 'Продажа товаров',
        // description: 'Оптовая партия ООО "ТоргСервис"',
        date: '2026-02-10 11:30:12',
        category: 'Доход',
        employee: {
            id: 'emp008',
            account_id: 'acc008',
            first_name: 'Дмитрий',
            last_name: 'Федоров',
            email: 'dmitry@company.ru',
            phone: '+79166789012',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-07-30',
            updated_at: '2026-02-03',
            linked_at: '2025-08-05'
        }
    },
    {
        amount: 4500,
        direction: 'minus',
        currency: 'ru',
        // title: 'Реклама и маркетинг',
        // description: 'Контекстная реклама Яндекс',
        date: '2026-02-10 09:15:55',
        category: 'Маркетинг',
        employee: {
            id: 'emp009',
            account_id: 'acc009',
            first_name: 'Ольга',
            last_name: 'Николаева',
            email: 'olga@company.ru',
            phone: '+79167890123',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-07-10',
            updated_at: '2026-02-02',
            linked_at: '2025-07-15'
        }
    },
    {
        amount: 6700,
        direction: 'plus',
        currency: 'us',
        // title: 'Freelance project',
        // description: 'Web development for Startup LLC',
        date: '2026-02-09 17:40:20',
        category: 'Доход',
        employee: {
            id: 'emp010',
            account_id: 'acc010',
            first_name: 'Иван',
            last_name: 'Смирнов',
            email: 'ivan@company.ru',
            phone: '+79168901234',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-06-20',
            updated_at: '2026-02-01',
            linked_at: '2025-06-25'
        }
    },
    {
        amount: 2300,
        direction: 'minus',
        currency: 'ru',
        // title: 'Канцелярия',
        // description: 'Офисные принадлежности',
        date: '2026-02-09 15:25:10',
        category: 'Офис',
        employee: {
            id: 'emp011',
            account_id: null,
            first_name: 'Анна',
            last_name: 'Волкова',
            email: 'anna@company.ru',
            phone: '+79169012345',
            status: 'active',
            is_account_linked: false,
            created_at: '2026-01-10',
            updated_at: '2026-01-31',
            linked_at: null
        }
    },
    {
        amount: 11200,
        direction: 'plus',
        currency: 'ea',
        // title: 'Консультационные услуги',
        // description: 'Бизнес-консалтинг EU Company',
        date: '2026-02-09 13:10:40',
        category: 'Доход',
        employee: {
            id: 'emp012',
            account_id: 'acc012',
            first_name: 'Sophie',
            last_name: 'Dubois',
            email: 'sophie@company.fr',
            phone: '+33123456789',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-05-25',
            updated_at: '2026-01-30',
            linked_at: '2025-05-30'
        }
    },
    {
        amount: 890,
        direction: 'minus',
        currency: 'kz',
        // title: 'Транспортные расходы',
        // description: 'Такси для сотрудников',
        date: '2026-02-09 10:55:18',
        category: 'Транспорт',
        employee: {
            id: 'emp013',
            account_id: 'acc013',
            first_name: 'Нурлан',
            last_name: 'Сагитов',
            email: 'nurlan@company.kz',
            phone: '+77022345678',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-05-05',
            updated_at: '2026-01-29',
            linked_at: '2025-05-10'
        }
    },
    {
        amount: 5600,
        direction: 'plus',
        currency: 'ru',
        // title: 'Абонентская плата',
        // description: 'Обслуживание ПО и сервисов',
        date: '2026-02-08 19:20:30',
        category: 'Доход',
        employee: {
            id: 'emp014',
            account_id: 'acc014',
            first_name: 'Павел',
            last_name: 'Орлов',
            email: 'pavel@company.ru',
            phone: '+79170123456',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-04-15',
            updated_at: '2026-01-28',
            linked_at: '2025-04-20'
        }
    },
    {
        amount: 3400,
        direction: 'minus',
        currency: 'ru',
        // title: 'Обучение сотрудников',
        // description: 'Курсы повышения квалификации',
        date: '2026-02-08 16:45:22',
        category: 'Обучение',
        employee: {
            id: 'emp015',
            account_id: 'acc015',
            first_name: 'Татьяна',
            last_name: 'Лебедева',
            email: 'tatyana@company.ru',
            phone: '+79171234567',
            status: 'active',
            is_account_linked: true,
            created_at: '2025-04-01',
            updated_at: '2026-01-27',
            linked_at: '2025-04-05'
        }
    }
];